; PlatformIO Project Configuration File for Lab 0: ESP32 Development Environment & Blink Test
; Documentation: https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; If you are using IPST-WiFi board, you can use:
; [env:ipst_wifi]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200
